
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Standing {
  name: string;
  ppg: number;
  wins: number;
  losses: number;
  points: number;
  played: number;
  isEligible?: boolean;
  bonusPoints?: number; // bagels
  clutchWins?: number;  // 11-10 wins
  noShows?: number;
  dragonBalls?: number;
}

interface SagaStats {
  totalMatches: number;
  minRequired?: number;
}

// --- CONFIG & THEME ---
const THEME = {
  bg: [11, 15, 20] as [number, number, number], // #0B0F14
  gold: [234, 179, 8] as [number, number, number], // #EAB308
  white: [255, 255, 255] as [number, number, number],
  slate: [100, 116, 139] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
};

const getPowerTitle = (ppg: number) => {
  if (ppg >= 3.5) return "ULTRA INSTINCT";
  if (ppg >= 3.0) return "SSGSS (BLUE)";
  if (ppg >= 2.5) return "SUPER SAIYAN GOD";
  if (ppg >= 2.0) return "SUPER SAIYAN";
  if (ppg >= 1.5) return "ELITE WARRIOR";
  return "EARTHLING";
};

// --- DRAWING HELPERS ---

const fillBackground = (doc: jsPDF) => {
  doc.setFillColor(...THEME.bg);
  doc.rect(0, 0, 210, 297, "F");
};

const drawBorder = (doc: jsPDF) => {
  doc.setDrawColor(...THEME.gold);
  doc.setLineWidth(1);
  doc.rect(10, 10, 190, 277); // Outer Frame
  
  // Corners
  doc.setLineWidth(3);
  doc.line(10, 10, 30, 10); // Top Left H
  doc.line(10, 10, 10, 30); // Top Left V
  
  doc.line(180, 10, 200, 10); // Top Right H
  doc.line(200, 10, 200, 30); // Top Right V
  
  doc.line(10, 267, 10, 287); // Bottom Left V
  doc.line(10, 287, 30, 287); // Bottom Left H
  
  doc.line(200, 267, 200, 287); // Bottom Right V
  doc.line(180, 287, 200, 287); // Bottom Right H
};

const drawWatermark = (doc: jsPDF) => {
  doc.saveGraphicsState();
  doc.setTextColor(30, 41, 59); // Very dark slate
  doc.setFontSize(150);
  doc.setFont("helvetica", "bold");
  // Rotate around center
  doc.text("S A G A", 105, 150, { align: "center", angle: 45 } as any);
  doc.restoreGraphicsState();
};

const drawHeader = (doc: jsPDF, title: string) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(...THEME.gold);
  doc.text(title.toUpperCase(), 105, 25, { align: "center" });
  
  doc.setDrawColor(...THEME.gold);
  doc.setLineWidth(0.5);
  doc.line(65, 28, 145, 28);
};

// --- MAIN GENERATOR ---

export const generateUltraSagaPdf = (
  sagaName: string,
  standings: Standing[],
  stats?: SagaStats
) => {
  const doc = new jsPDF();
  
  // Sort strictly by SAGA PPG LAW
  const sorted = [...standings].sort((a, b) => {
    // 1. PPG (Primary)
    if (Math.abs(b.ppg - a.ppg) > 0.000001) return b.ppg - a.ppg;
    
    // 2. Total Points
    if (b.points !== a.points) return b.points - a.points;
    
    // 3. Wins
    if (b.wins !== a.wins) return b.wins - a.wins;
    
    // 4. Games Played
    return b.played - a.played;
  });

  const champion = sorted[0];
  const top3 = sorted.slice(0, 3);

  // =====================================
  // PAGE 1 — COVER
  // =====================================
  fillBackground(doc);
  drawBorder(doc);
  drawWatermark(doc);

  // Title Block
  doc.setTextColor(...THEME.white);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("OFFICIAL BATTLE REPORT", 105, 60, { align: "center" });

  doc.setTextColor(...THEME.gold);
  doc.setFontSize(48);
  doc.text("DRAGON BALL Z", 105, 80, { align: "center" });
  
  doc.setFontSize(28);
  doc.setTextColor(...THEME.white);
  doc.text(sagaName.toUpperCase(), 105, 95, { align: "center" });

  // Champion Highlight
  if (champion) {
    const startY = 130;
    
    // Crown/Label
    doc.setFillColor(30, 41, 59);
    doc.setDrawColor(...THEME.gold);
    doc.roundedRect(65, startY, 80, 50, 2, 2, "FD");

    doc.setFontSize(12);
    doc.setTextColor(...THEME.gold);
    doc.text("SAGA CHAMPION", 105, startY + 12, { align: "center" });

    doc.setFontSize(28);
    doc.setTextColor(...THEME.white);
    doc.text(champion.name.toUpperCase(), 105, startY + 28, { align: "center" });

    doc.setFontSize(10);
    doc.setTextColor(...THEME.slate);
    doc.text(`${champion.ppg.toFixed(2)} PPG`, 105, startY + 40, { align: "center" });
    
    // Power Level
    doc.setFontSize(14);
    doc.setTextColor(...THEME.red);
    doc.text(getPowerTitle(champion.ppg), 105, startY + 65, { align: "center" });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...THEME.slate);
  doc.text("GENERATED BY COURT OS", 105, 275, { align: "center" });

  doc.addPage();

  // =====================================
  // PAGE 2 — PODIUM OF POWER
  // =====================================
  fillBackground(doc);
  drawBorder(doc);
  drawHeader(doc, "PODIUM OF POWER");

  // Draw Podium Steps (Rectangles)
  const baseY = 220;
  const pWidth = 50;
  
  // 2nd Place (Left)
  if (top3[1]) {
    const h = 60;
    doc.setFillColor(192, 192, 192); // Silver
    doc.rect(35, baseY - h, pWidth, h, "F");
    
    doc.setTextColor(...THEME.white);
    doc.setFontSize(16);
    doc.text(top3[1].name.toUpperCase(), 60, baseY - h - 10, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(...THEME.gold);
    doc.text(`${top3[1].ppg.toFixed(2)} PPG`, 60, baseY - h - 4, { align: "center" });
    
    doc.setFontSize(30);
    doc.setTextColor(30, 30, 30);
    doc.text("2", 60, baseY - 25, { align: "center" });
  }

  // 1st Place (Center - Highest)
  if (top3[0]) {
    const h = 80;
    doc.setFillColor(...THEME.gold); 
    doc.rect(80, baseY - h, pWidth, h, "F");

    doc.setTextColor(...THEME.white);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(top3[0].name.toUpperCase(), 105, baseY - h - 15, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(...THEME.gold);
    doc.text(`${top3[0].ppg.toFixed(2)} PPG`, 105, baseY - h - 6, { align: "center" });

    doc.setFontSize(40);
    doc.setTextColor(50, 30, 0);
    doc.text("1", 105, baseY - 35, { align: "center" });
  }

  // 3rd Place (Right)
  if (top3[2]) {
    const h = 40;
    doc.setFillColor(205, 127, 50); // Bronze
    doc.rect(125, baseY - h, pWidth, h, "F");

    doc.setTextColor(...THEME.white);
    doc.setFontSize(16);
    doc.text(top3[2].name.toUpperCase(), 150, baseY - h - 10, { align: "center" });
    
    doc.setFontSize(10);
    doc.setTextColor(...THEME.gold);
    doc.text(`${top3[2].ppg.toFixed(2)} PPG`, 150, baseY - h - 4, { align: "center" });

    doc.setFontSize(30);
    doc.setTextColor(50, 20, 0);
    doc.text("3", 150, baseY - 15, { align: "center" });
  }

  doc.addPage();

  // =====================================
  // PAGE 3 — FULL STANDINGS
  // =====================================
  fillBackground(doc);
  drawHeader(doc, "FULL STANDINGS");

  const tableRows = sorted.map((p, i) => [
    i + 1,
    p.name.toUpperCase(),
    p.ppg.toFixed(2),
    `${p.wins}-${p.losses}`,
    p.played,
    p.points,
    p.isEligible ? "ELIGIBLE" : "< 60%"
  ]);

  autoTable(doc, {
    startY: 40,
    head: [['#', 'FIGHTER', 'PPG', 'W-L', 'M', 'PTS', 'STATUS']],
    body: tableRows,
    theme: 'grid',
    styles: {
      fillColor: [15, 23, 42], // Slate 900
      textColor: [255, 255, 255],
      font: "helvetica",
      fontSize: 10,
      lineColor: [30, 41, 59],
      lineWidth: 0.1
    },
    headStyles: {
      fillColor: THEME.gold,
      textColor: [0, 0, 0],
      fontStyle: "bold",
      halign: 'center'
    },
    columnStyles: {
      0: { halign: 'center', fontStyle: 'bold', cellWidth: 15 },
      2: { halign: 'center', fontStyle: 'bold', textColor: THEME.gold },
      3: { halign: 'center' },
      4: { halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'center', fontSize: 8 }
    },
    alternateRowStyles: {
      fillColor: [11, 15, 20]
    }
  });

  doc.addPage();

  // =====================================
  // PAGE 4 — SPECIAL ATTACKS
  // =====================================
  fillBackground(doc);
  drawHeader(doc, "SPECIAL ATTACKS");

  // Bagels Section
  let yPos = 50;
  doc.setTextColor(...THEME.gold);
  doc.setFontSize(16);
  doc.text("BAGELS (11-0 WINS)", 15, yPos);
  
  yPos += 10;
  
  const bagelPlayers = sorted.filter(p => p.bonusPoints && p.bonusPoints > 0);
  
  if (bagelPlayers.length > 0) {
    const bagelRows = bagelPlayers.map(p => [p.name.toUpperCase(), `${p.bonusPoints} BAGELS`]);
    autoTable(doc, {
        startY: yPos,
        head: [['FIGHTER', 'COUNT']],
        body: bagelRows,
        theme: 'grid',
        styles: { fillColor: [15, 23, 42], textColor: 255 },
        headStyles: { fillColor: [59, 130, 246], textColor: 255 }, // Blue header for bagels
    });
    yPos = (doc as any).lastAutoTable.finalY + 20;
  } else {
    doc.setTextColor(...THEME.slate);
    doc.setFontSize(12);
    doc.text("No bagels served this saga.", 15, yPos + 5);
    yPos += 20;
  }

  // Destructo Disc Section
  doc.setTextColor(...THEME.gold);
  doc.setFontSize(16);
  doc.text("DESTRUCTO DISC (11-10 WINS)", 15, yPos);
  yPos += 10;

  const clutchPlayers = sorted.filter(p => p.clutchWins && p.clutchWins > 0);
  
  if (clutchPlayers.length > 0) {
    const clutchRows = clutchPlayers.map(p => [p.name.toUpperCase(), `${p.clutchWins} CLUTCH WINS`]);
    autoTable(doc, {
        startY: yPos,
        head: [['FIGHTER', 'COUNT']],
        body: clutchRows,
        theme: 'grid',
        styles: { fillColor: [15, 23, 42], textColor: 255 },
        headStyles: { fillColor: [239, 68, 68], textColor: 255 }, // Red header for clutch
    });
  } else {
    doc.setTextColor(...THEME.slate);
    doc.setFontSize(12);
    doc.text("No clutch finishes recorded.", 15, yPos + 5);
  }

  doc.addPage();

  // =====================================
  // FINAL PAGE — QUOTE
  // =====================================
  fillBackground(doc);
  drawBorder(doc);
  
  doc.setTextColor(...THEME.gold);
  doc.setFontSize(16);
  doc.text("LEGENDS ARE FORGED IN BATTLE", 105, 130, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(...THEME.white);
  doc.text('"Train Harder. Play Harder. Ascend Higher."', 105, 145, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(...THEME.slate);
  doc.text("COURT OS", 105, 275, { align: "center" });

  doc.save(`${sagaName.replace(/\s+/g, '_')}_ULTRA_REPORT.pdf`);
};
